### ISSUE TITLE
Build failing due to API change in jeffail/tunny

### ISSUE THREAD

**Issue by astax-t** [dyatlov/proclink-api#3]
Jeffail has updated his [package](https://github.com/Jeffail/tunny) API and this now breaks the build.

He has provided some recommendations for fixing the problem here - https://github.com/Jeffail/tunny/issues/19

**Comment by dyatlov** [comment]
Hi,
Thanks for the notice!
It's actually to verbose and bloated for such simple task.
I just axed it completely from server code, see: https://github.com/dyatlov/proclink-api/commit/bd1c79e9fe114919e821422cdb8346030e92ae36
All seems to work fine.

**Comment by astax-t** [comment]
Ah, even better. Yay for simplicity!
